# Generated by Django 5.2.9 on 2025-12-17 21:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.CharField(help_text='Target URL to crawl', max_length=500)),
                ('crawl_type', models.CharField(choices=[('news_list', 'News List'), ('article', 'Single Article'), ('channel', 'Full Channel')], default='news_list', help_text='Type of crawl operation', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current task status', max_length=20)),
                ('total_items', models.PositiveIntegerField(default=0, help_text='Number of items crawled')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed')),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for tracking', max_length=255)),
            ],
            options={
                'verbose_name': 'Crawl Task',
                'verbose_name_plural': 'Crawl Tasks',
                'db_table': 'crawl_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cont_id', models.CharField(db_index=True, help_text='ThePaper content ID', max_length=50)),
                ('url', models.CharField(help_text='Article URL', max_length=500)),
                ('title', models.CharField(help_text='Article title', max_length=500)),
                ('author', models.CharField(blank=True, help_text='Article author', max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Article summary')),
                ('content_text', models.TextField(blank=True, help_text='Full article text')),
                ('channel_id', models.IntegerField(blank=True, help_text='Channel node ID', null=True)),
                ('channel_name', models.CharField(blank=True, help_text='Channel name', max_length=100)),
                ('publish_time', models.DateTimeField(blank=True, help_text='Article publish time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.JSONField(default=list, help_text='List of tag objects')),
                ('neo4j_synced', models.BooleanField(db_index=True, default=False, help_text='Whether synced to Neo4j')),
                ('task', models.ForeignKey(help_text='Parent crawl task', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crawl.crawltask')),
            ],
            options={
                'verbose_name': 'Crawl Item',
                'verbose_name_plural': 'Crawl Items',
                'db_table': 'crawl_item',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'neo4j_synced'], name='crawl_item_task_id_8b55d6_idx')],
            },
        ),
    ]
