# Generated by Django 5.2.9 on 2025-12-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_add_unique_cont_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawltask',
            name='media_crawl_enabled',
            field=models.BooleanField(default=False, help_text='Whether to trigger media platform crawl for this task'),
        ),
        migrations.AddField(
            model_name='crawltask',
            name='media_platform',
            field=models.CharField(blank=True, choices=[('', 'None'), ('bilibili', 'Bilibili'), ('douyin', 'Douyin'), ('kuaishou', 'Kuaishou'), ('weibo', 'Weibo'), ('xhs', 'Xiaohongshu'), ('tieba', 'Tieba'), ('zhihu', 'Zhihu')], default='', help_text='Target media platform for crawl (optional)', max_length=20),
        ),
    ]
