# Generated by Django 5.2.9 on 2025-12-21 04:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_crawl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='报告标题', max_length=255)),
                ('platform', models.CharField(db_index=True, help_text='平台名称', max_length=50)),
                ('source_keyword', models.CharField(db_index=True, help_text='来源关键词', max_length=255)),
                ('time_from', models.BigIntegerField(blank=True, help_text='时间范围起始', null=True)),
                ('time_to', models.BigIntegerField(blank=True, help_text='时间范围结束', null=True)),
                ('content', models.TextField(help_text='报告内容 (Markdown)')),
                ('record_count', models.IntegerField(default=0, help_text='分析的记录数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
            options={
                'verbose_name': '分析报告',
                'verbose_name_plural': '分析报告',
                'db_table': 'analysis_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
